import HomePosts from "@/components/homePosts/homePosts";
import Navbar from "@/components/navbar/navbar";
import { getUser } from "@/lib/firebase";
import { Box, CircularProgress } from "@mui/material";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import styles from './home.module.scss'
import Background from "@/components/bacground/background";
import Head from "next/head";
export default function Home() {
  const [loading, setLoading] = useState(true);
  const [locakUser, setLocalUser] = useState("");

  let router = useRouter();
  useEffect(() => {
    async function chekInfo() {
      let key = localStorage.getItem("USER");
      if (key) {
        var result = await getUser(key);
        setLocalUser(result);
       
      }
      if (!result) {
        localStorage.removeItem("USER");
        router.push("/login");
      } else {
        setLoading(false);
      }
    }
    chekInfo();
  }, []);
  return (
    <>
     <Head>
        <title>Social Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      {loading ? (
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            width: "100%",
            height: "100vh",
          }}
        >
          <CircularProgress />
        </Box>
      ) : (
        <>
            <Background/>

          <div className={styles.home}>
          <Navbar />
          <HomePosts localUser={locakUser}/>
          </div>
        </>
      )}
    </>
  );
}
