import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useEffect } from 'react'
import { getUser } from '@/lib/firebase'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  let router = useRouter()
  useEffect(()=>{
    async function chekInfo(){
      let key = localStorage.getItem('USER')
        if(key){
            var result = await getUser(key)
        }
      if(result){
        router.push('/home')
      }
      else{
        localStorage.removeItem('USER')
        router.push('/login')
      }
    }
    chekInfo()
  },[])
  return (
    <>
      <Head>
        <title>Social Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
    </>
  )
}